export interface PawnItem {
  id: string;
  name: string;
  region: string;
}

export const PAWN_ITEMS: PawnItem[] = [
  { id: "1", name: "Rosetta Stone replica", region: "Egypt" },
  { id: "2", name: "Terracotta Army miniature", region: "China" },
  { id: "3", name: "Fabergé egg", region: "Russia" },
  { id: "4", name: "Antikythera mechanism fragment", region: "Greece" },
  { id: "5", name: "Dead Sea Scrolls fragment", region: "Middle East" },
  { id: "6", name: "Hope Diamond replica", region: "India" },
  { id: "7", name: "Bayeux Tapestry section", region: "France" },
  { id: "8", name: "Book of Kells page", region: "Ireland" },
  { id: "9", name: "Moai statue head", region: "Easter Island" },
  { id: "10", name: "Sutton Hoo helmet", region: "England" },
  { id: "11", name: "Mask of Tutankhamun", region: "Egypt" },
  { id: "12", name: "Venus de Milo miniature", region: "Greece" },
  { id: "13", name: "Code of Hammurabi stele", region: "Mesopotamia" },
  { id: "14", name: "Nebra sky disk", region: "Germany" },
  { id: "15", name: "Magna Carta copy", region: "England" },
  { id: "16", name: "Gutenberg Bible page", region: "Germany" },
  { id: "17", name: "Shroud of Turin piece", region: "Italy" },
  { id: "18", name: "Cyrus Cylinder", region: "Persia" },
  { id: "19", name: "Phaistos Disc", region: "Crete" },
  { id: "20", name: "Behistun Inscription rubbing", region: "Iran" },
  { id: "21", name: "Nazca Lines pottery", region: "Peru" },
  { id: "22", name: "Aztec Sun Stone replica", region: "Mexico" },
  { id: "23", name: "Crystal skull", region: "Mesoamerica" },
  { id: "24", name: "Voynich manuscript page", region: "Unknown" },
  { id: "25", name: "Bust of Nefertiti", region: "Egypt" },
  { id: "26", name: "Winged Victory of Samothrace", region: "Greece" },
  { id: "27", name: "Elgin Marbles fragment", region: "Greece" },
  { id: "28", name: "Ishtar Gate brick", region: "Babylon" },
  { id: "29", name: "Lycurgus Cup piece", region: "Rome" },
  { id: "30", name: "Portland Vase shard", region: "Rome" },
  { id: "31", name: "Staffordshire Hoard item", region: "England" },
  { id: "32", name: "Lewis chessmen figure", region: "Scotland" },
  { id: "33", name: "Tariq ibn Ziyad's sword replica", region: "Spain/Morocco" },
  { id: "34", name: "Charlemagne's crown replica", region: "Francia" },
  { id: "35", name: "Iron Crown of Lombardy", region: "Italy" },
  { id: "36", name: "Holy Lance replica", region: "Jerusalem" },
  { id: "37", name: "Crown of Thorns relic", region: "Jerusalem" },
  { id: "38", name: "True Cross fragment", region: "Jerusalem" },
  { id: "39", name: "Spear of Destiny", region: "Rome" },
  { id: "40", name: "Ark of the Covenant model", region: "Israel" },
  { id: "41", name: "Excalibur replica", region: "Britain" },
  { id: "42", name: "Mjolnir pendant", region: "Scandinavia" },
  { id: "43", name: "Gungnir spearhead", region: "Scandinavia" },
  { id: "44", name: "Kusanagi-no-Tsurugi replica", region: "Japan" },
  { id: "45", name: "Yata no Kagami mirror", region: "Japan" },
  { id: "46", name: "Yasakani no Magatama jewel", region: "Japan" },
  { id: "47", name: "Xiangqi set from Ming Dynasty", region: "China" },
  { id: "48", name: "Mahjong tiles from Qing Dynasty", region: "China" },
  { id: "49", name: "Go board from Edo Period", region: "Japan" },
  { id: "50", name: "Chess set from Soviet era", region: "Russia" },
  { id: "51", name: "Senet game board", region: "Egypt" },
  { id: "52", name: "Royal Game of Ur board", region: "Mesopotamia" },
  { id: "53", name: "Mancala board from Mali Empire", region: "Africa" },
  { id: "54", name: "Pachisi board from Mughal Empire", region: "India" },
  { id: "55", name: "Hnefatafl from Viking Age", region: "Scandinavia" },
  { id: "56", name: "Patolli game mat", region: "Mesoamerica" },
  { id: "57", name: "Ulama ball", region: "Mesoamerica" },
  { id: "58", name: "Tlachtli ring", region: "Mesoamerica" },
  { id: "59", name: "Cuju ball", region: "China" },
  { id: "60", name: "Kemari ball", region: "Japan" },
  { id: "61", name: "Buzkashi whip", region: "Central Asia" },
  { id: "62", name: "Polo mallet from Persian Empire", region: "Persia" },
  { id: "63", name: "Golf club from Scotland", region: "Scotland" },
  { id: "64", name: "Cricket bat from British Empire", region: "England" },
  { id: "65", name: "Baseball glove from early USA", region: "USA" },
  { id: "66", name: "Astrolabe from Islamic Golden Age", region: "Middle East" },
  { id: "67", name: "Armillary sphere from Renaissance", region: "Europe" },
  { id: "68", name: "Sextant from Age of Discovery", region: "Europe" },
  { id: "69", name: "Compass from Song Dynasty", region: "China" },
  { id: "70", name: "Telescope from Galileo's time", region: "Italy" },
  { id: "71", name: "Microscope from Leeuwenhoek's time", region: "Netherlands" },
  { id: "72", name: "Thermometer from Fahrenheit's time", region: "Germany" },
  { id: "73", name: "Barometer from Torricelli's time", region: "Italy" },
  { id: "74", name: "Seismograph from Han Dynasty", region: "China" },
  { id: "75", name: "Water clock from Ancient Greece", region: "Greece" },
  { id: "76", name: "Sundial from Ancient Rome", region: "Rome" },
  { id: "77", name: "Hourglass from Middle Ages", region: "Europe" },
  { id: "78", name: "Mechanical clock gear from 14th century", region: "Europe" },
  { id: "79", name: "Pocket watch from 16th century", region: "Germany" },
  { id: "80", name: "Wristwatch from WWI", region: "Europe" },
  { id: "81", name: "Samurai armor plate", region: "Japan" },
  { id: "82", name: "Knight's gauntlet", region: "Europe" },
  { id: "83", name: "Roman legionary shield fragment", region: "Rome" },
  { id: "84", name: "Viking shield boss", region: "Scandinavia" },
  { id: "85", name: "Zulu cowhide shield", region: "South Africa" },
  { id: "86", name: "Maori mere club", region: "New Zealand" },
  { id: "87", name: "Aboriginal boomerang", region: "Australia" },
  { id: "88", name: "Inuit bone carving", region: "Arctic" },
  { id: "89", name: "Native American dreamcatcher", region: "North America" },
  { id: "90", name: "Hawaiian lei niho palaoa", region: "Hawaii" },
  { id: "91", name: "Inca quipu", region: "Peru" },
  { id: "92", name: "Maya codex page", region: "Mesoamerica" },
  { id: "93", name: "Olmec colossal head replica", region: "Mexico" },
  { id: "94", name: "Toltec warrior statue replica", region: "Mexico" },
  { id: "95", name: "Zapotec urn", region: "Mexico" },
  { id: "96", name: "Moche portrait vessel", region: "Peru" },
  { id: "97", name: "Chimu silver cup", region: "Peru" },
  { id: "98", name: "Tiwanaku monolith piece", region: "Bolivia" },
  { id: "99", name: "Valdivia figurine", region: "Ecuador" },
  { id: "100", name: "San Agustín sculpture piece", region: "Colombia" },
];

let usedItems = new Set<string>();

export function getRandomPawnItem(): PawnItem {
  let availableItems = PAWN_ITEMS.filter(item => !usedItems.has(item.id));
  if (availableItems.length === 0) {
    usedItems.clear();
    availableItems = PAWN_ITEMS;
  }
  const randomItem = availableItems[Math.floor(Math.random() * availableItems.length)];
  usedItems.add(randomItem.id);
  return randomItem;
}
